### ISSUE TITLE
Some rules are skipped

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/DeadDomainsLinter#14] opened 2024-01-30 15:24 UTC
Testing rules, `wq3.ru` is dead:
```
http://wq3.ru^$third-party
http://wwq3.ru^$third-party
http://www.wwq3.ru^$third-party
http://wq3.ru^

https://wq3.ru^$third-party
https://wwq3.ru^$third-party
https://www.wwq3.ru^$third-party
https://wq3.ru^

wq3.ru^$third-party
wwq3.ru^$third-party
www.wwq3.ru^$third-party
wq3.ru^

||wq3.ru^$third-party
||wwq3.ru^$third-party
||www.wwq3.ru^$third-party
||wq3.ru^
```

### Expected result

All rules removed.

### Actual result

Removed only
`||wwq3.ru^$third-party`
`||www.wwq3.ru^$third-party`

![image](https://github.com/AdguardTeam/DeadDomainsLinter/assets/8361299/c0325104-36d5-4175-a4b7-6022054dda92)

Probably it will be fixed by https://github.com/AdguardTeam/DeadDomainsLinter/issues/11 
Will check after update.

**Comment by ameshkov** [comment] 2024-01-30 15:31
```
wq3.ru^$third-party
wwq3.ru^$third-party
www.wwq3.ru^$third-party
wq3.ru^
```

These shouldn't be removed, we cannot be sure that it's a domain name.

**Comment by ameshkov** [comment] 2024-01-30 15:31
And yeah, duplicate of #11

**Closed by ameshkov** 2024-01-30 15:31 UTC

**Comment by Alex-302** [comment] 2024-01-30 17:40
Ok
